---
- name: Install mopidy and nodejs
  become: yes
  apt: name=mopidy,nodejs state=latest

- name: Give the mopidy user a shell
  become: yes
  user: name=mopidy shell=/bin/bash

- name: Add the node modules path to the mopidy users bash profile
  become: yes
  become_user: mopidy
  blockinfile:
    path: /var/lib/mopidy/.bash_profile
    create: yes
    block: |
      export NODE_PATH="/usr/lib/node_modules"

- name: Install testing packages globally
  become: yes
  npm: name={{ item }} global=yes
  with_items:
  - amdefine
  - requirejs
  - mocha
  - testdouble
  - squirejs
  - when
  - mopidy

- name: Install all required mopidy extensions
  become: yes
  become_user: mopidy
  pip: name=Mopidy-Local-SQLite,Mopidy-Local-Images

- name: Add the mopidy key for their repo
  become: yes
  apt_key: url=https://apt.mopidy.com/mopidy.gpg state=present

- name: Add mopidy repo
  become: yes
  apt_repository: repo="deb http://apt.mopidy.com/ stretch main contrib non-free" state=present

- name: Add mopidy src repo
  become: yes
  apt_repository: repo="deb-src http://apt.mopidy.com/ stretch main contrib non-free" state=present

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install mopidy-spotify (doesnt work with pip above)
  become: yes
  apt: name=mopidy-spotify state=latest

- name: Remove mopidy repo
  become: yes
  apt_repository: repo="deb http://apt.mopidy.com/ stretch main contrib non-free" state=absent

- name: Remove mopidy src repo
  become: yes
  apt_repository: repo="deb-src http://apt.mopidy.com/ stretch main contrib non-free" state=absent

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install the mopidy pi client from our synced folder
  become: yes
  become_user: mopidy
  pip: name=file:///mopidy-pi-client extra_args=-e

- name: Change default mopidy config
  become: yes
  template: src=mopidy.conf.tpl dest=/etc/mopidy/mopidy.conf

- name: Restart mopidy
  become: yes
  service: name=mopidy enabled=yes state=restarted

- name: Rescan for music on mopidy
  command: mopidyctl local scan
  become: yes
